### ISSUE TITLE
Philosophy: code formatting

### ISSUE THREAD

**Issue by BBI-YggyKing** [Mervill/UnityLitJson#3]
_Should we preserve the code conventions (formatting, indents, naming, etc.) of the LitJson or overhaul them?_

The original LitJson package uses tabs, put opening brace at the end of the line, and inserts spaces before method parameters and method call arguments. Should we preserve this format, or update to (for example) [MSDN-style standards](http://msdn.microsoft.com/en-us/library/ff926074.aspx)?

Preserving the existing format may simplify integration of changes from disparate sources. But if we're going to change it, now's the time.

**Comment by BBI-YggyKing** [comment]
I don't like the current formatting and would much prefer the MSDN style. (Which are the default code formatting settings in Visual Studio, where I do most of my editing.)

**Comment by Mervill** [comment]
IIRC reformatting the project will remove previous blame/contribution tags. For example if you look at an arbitrary file it shows that several people have contributed to it, (and links back to their user page, etc) reformatting eliminates those tags and make the pusher the sole contributor to a file.

Personally I don't care, but some people do, so I though't id mention it.

As for style, MSDN is fine. I generally like to keep my opening braces on the preceding line `void Foo(){` but that's because I spent my formative years in languages that eschew braces altogether. I understand the readability angle but it feels to me like they get in the way when their on their own line.

I'll cede to experience on this decision. Format the project however you think is best.
